/*
 * @(#)Faculty.java      0.1 13/01/16
 * 
 * The Admissions Committee Web System.
 * Kiev, Ukraine.
 */
package ua.epam.kalko.domain;

/**
 * Entity object, which represents Faculty.
 *
 * @version 0.1 16 Jan 2013.
 * @author Kalko Ievgen.
 */
public class Faculty {

    /**
     * Stores faculty id, auto generated by DB.
     */
    private int id;
    /**
     * Faculty title.
     */
    private String name;
    /**
     * Faculty abbreviation.
     */
    private String facullty_abbreviation;
    /**
     * Min pass mark, which should be get by enrollee.
     */
    private double passMark;
    /**
     * Max number of enrollees on faculty.
     */
    private int quota;

    /**
     * Main constructor.
     *
     * @param id
     * @param name
     * @param facullty_abbreviation
     * @param passMark
     * @param quota
     */
    public Faculty(int id, String name, String facullty_abbreviation,
            double passMark, int quota) {
        this.id = id;
        this.name = name;
        this.facullty_abbreviation = facullty_abbreviation;
        this.passMark = passMark;
        this.quota = quota;
    }

    /* Setters and getters */
    public String getName() {
        return name;
    }

    public int getQuota() {
        return quota;
    }

    public double getPassMark() {
        return passMark;
    }

    public String getFacullty_abbreviation() {
        return facullty_abbreviation;
    }

    public int getId() {
        return id;
    }
}
